# Generated by Django 3.1.4 on 2020-12-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applying_in',
            field=models.CharField(choices=[('Backend', 'backend'), ('Mobile,', 'mobile')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
    ]
